import Head from 'next/head'
import Header from '../src/components/Header'
import Hero from '../src/components/Hero'
import Perks from '../src/components/Perks'
import FreeDay from '../src/components/FreeDay'
import Location from '../src/components/Location'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Perks />
      <FreeDay />
      <Location />
    </div>
  )
}
